# DeepSource configuration file - verified with official documentation
version = 1

# Files to exclude from analysis
exclude_patterns = [
  "**/node_modules/**",
  "**/dist/**", 
  "**/build/**",
  "**/*.min.js",
  "**/*.min.css",
  "**/.ipynb_checkpoints/**"
]

# Identify test files
test_patterns = [
  "**/test/**",
  "**/*.test.js",
  "**/*.spec.js",
  "**/*_test.py"
]

# JavaScript analyzer - for JavaScript Algorithms, Front End Development
[[analyzers]]
name = "javascript"
enabled = true
dependency_file_paths = [
  "package.json",
  "package-lock.json",
  "yarn.lock"
]

# Python analyzer - for Scientific Computing, Data Analysis, Machine Learning
[[analyzers]]
name = "python"
enabled = true
python_version = "3.x"
dependency_file_paths = [
  "requirements.txt",
  "Pipfile",
  "setup.py"
]

# SQL analyzer - for Relational Database certification
[[analyzers]]
name = "sql"
enabled = true

# Shell scripts - for Bash scripting in Relational Database cert
[[analyzers]]
name = "shell"
enabled = true

# Security analysis - especially for Information Security certification
[[analyzers]]
name = "secrets"
enabled = true

# Test Coverage analyzer - for when you add tests in the future
[[analyzers]]
name = "test-coverage"
enabled = true

# Optional: Enable these if relevant to your curriculum
# Ruby analyzer
[[analyzers]]
name = "ruby"
enabled = true

# Go analyzer
[[analyzers]]
name = "go"
enabled = true

# Transformers - based on commonly supported ones
[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "isort"
enabled = true
