name: Update freeCodeCamp Activity

on:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape-activity:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install puppeteer fs
        
      - name: Run scraper
        env:
          FCC_USERNAME: ${{ secrets.FCC_USERNAME }}
        run: node scripts/scrape-activity.js
          
      - name: Commit & Push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add activity-data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update activity data [skip ci]"
          git push
